pipeline:
  options:
    skipDefaultCheckout: true
  dockerBuilds:
    main:
      image: 611706558220.dkr.ecr.us-west-2.amazonaws.com/service-template
      dockerfile: _infra/Dockerfile
  post:
    onSuccess:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: "Successful build of service-template version ${REF}: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>"
    onError:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: "Build failed for service-template version ${REF}: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>"
