pipeline:
  version: 2
  options:
    skipDefaultCheckout: true
  phases:
  - stages:
    - name: hello
      steps:
      - type: sendSlackMessage
        to: "C03EZGK6CTF"
        message: "CD of srv template is triggered"