version: '3'
services:
  web:
    image: service-template:localbuild
    container_name: service-template.web
    build:
      context: .
      args:
        - PIP_EXTRA_INDEX_URL
    environment:
      - GIT_TAG=localbuild
      - ENVIRONMENT=local
    ports:
      - 80:80
