version: '3'
services:
  service-template.web:
    container_name: service-template.web
    build:
      context: .
      args:
        - PIP_EXTRA_INDEX_URL
    image: service-template:localbuild
    ports:
      - 80:80
    volumes:
      - $PWD/application:/home/app/application
      - ${RUNTIME_PATH:-./empty_runtime}/data:/srv/runtime/current/data