pipeline:
  stages:
    Hotfix:
      steps:
        - type: deployService
    Deploy Pulse:
      steps:
        - type: deployPulse
  post:
    onSuccess:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: "Successful hotfix of service-template to ${REF} in prod: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>"
    onError:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: "Hotfix failed for service-template to ${REF} in prod: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>"
