@Library('common-pipelines@v9.0.33') _

def common
docker = new org.doordash.Docker()
github = new org.doordash.Github()
os = new org.doordash.Os()

// -----------------------------------------------------------------------------------
// The following params are automatically provided by the callback gateway as inputs
// to the Jenkins pipeline that starts this job.
//
// params["SHA"]                    - Sha used to start the pipeline
// params["BRANCH_NAME"]            - Name of GitHub branch the SHA is associated with
// params["UNIQUE_BUILD_ID"]        - A randomly generated unique ID for this job run
// params["ENQUEUED_AT_TIMESTAMP"]  - Unix timestamp generated by callback gateway
// params["JSON"]                   - Extensible json doc with extra information
// params["GITHUB_REPOSITORY"]      - GitHub ssh url of repository (git://....)
// -----------------------------------------------------------------------------------

serviceId = github.describeGitUrlParts(params["GITHUB_REPOSITORY"])["repository"]

stage('Startup') {
  curlSlave {
    os.deleteDirContentsAsRoot()
    github.fastCheckoutScm(params["GITHUB_REPOSITORY"], params["SHA"])
    common = (new org.doordash.PipelineHelper()).loadLocalFile("Jenkinsfile-common.groovy")
    github.sendStatusToGitHub(
      params["SHA"],
      params["GITHUB_REPOSITORY"],
      "Started.",
      "Start Jenkinsfile-deploy Pipeline",
      "${BUILD_URL}console"
    )
  }
}

common.buildImages(params["GITHUB_REPOSITORY"], params["SHA"], serviceId)

common.runTests(params["GITHUB_REPOSITORY"], params["SHA"], serviceId)

stage('Deploy to staging') {
  genericSlave {
    doKubernetesDeploy('staging', 'staging')
  }
}

stage('Deploy to prod') {
  try {
    timeout(time: 10, unit: 'MINUTES') {
        input 'Deploy to production?'
    }
  } catch(err) {
    error('Aborted due to timeout!')
  }
  genericSlave {
    doKubernetesDeploy('prod', 'prod')
  }
}

def doKubernetesDeploy(targetCluster, targetFabric) {
  os.deleteDirContentsAsRoot()
  github.fastCheckoutScm(params["GITHUB_REPOSITORY"], params["SHA"], serviceId)
  withCredentials([file(credentialsId: 'K8S_CONFIG_' + targetCluster.toUpperCase(), variable: 'k8CredsFile'), string(credentialsId: 'PIP_EXTRA_INDEX_URL', variable: 'PIP_EXTRA_INDEX_URL')]) {
    sh """|#!/bin/bash
          |set -x
          |cd ${serviceId}
          |PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL} make \\
          | fabric="${targetFabric}" \\
          | vars="git_sha=${params["SHA"]}" \\
          | k8-credentials-file="${k8CredsFile}" \\
          | deploy
          |""".stripMargin()
  }
} 
