pipeline:
  version: 2
  options:
    timeout:
      time: 60
      unit: minutes
  phases:
  - stages:
    - name: Migrate
      steps:
      - type: migrateService
    post:
      onSuccess:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: 'Successful migrate of service-template to ${REF} in ${ENV}: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>'
      onError:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: 'Migrate failed for service-template to ${REF} in ${ENV}: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>'
