pipeline:
  stages:
    Promote to staging:
      steps:
        - type: deployService
          environment: staging
    Deploy Pulse to staging:
      steps:
        - type: deployPulse
          environment: staging
          mode: blocking
    Promote to prod:
      steps:
        - type: deployService
          environment: prod
    Deploy Pulse to prod:
      steps:
        - type: deployPulse
          environment: prod
          mode: blocking
  post:
    onSuccess:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: "Successful promote of service-template to ${REF} in ${ENV}: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>"
    onError:
      - type: sendSlackMessage
        to: "#pulse-svc-template"
        message: "Promote failed for service-template to ${REF} in ${ENV}: <${BUILD_URL}|${JOB_NAME} [${BUILD_NUMBER}]>"
