apiVersion: v1
kind: Service
metadata:
  name: {{service}}
  labels:
    app: {{service}}
spec:
  selector:
    app: {{service}}
  ports:
    - protocol: TCP
      port: 80
      name: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{service}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: {{service}}
    spec:
      containers:
      - name: web
        image: {{aws_account}}.dkr.ecr.us-west-2.amazonaws.com/doordash/{{service}}.app:{{git_sha}}
        command: ["/root/docker/entrypoint.sh"]
        args: ["/root/docker/run.sh"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{service}}-aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{service}}-aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: FABRIC
          value: {{fabric}}
        - name: SERVICE_NAME
          value: {{service}}
