apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}
      app: web
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}
        app: web
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      volumes:
      - name: runtime-volume
        emptyDir: {}
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command: ["/home/app/entrypoint.sh"]
        args: ["/home/app/run.sh"]
        resources:
          limits:
            cpu: {{ .Values.web.resources.limits.cpu }}
            memory: {{ .Values.web.resources.limits.memory }}
          requests:
            cpu: {{ .Values.web.resources.requests.cpu }}
            memory: {{ .Values.web.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        volumeMounts:
          - name: runtime-volume
            mountPath: /srv/runtime
            readOnly: true
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-environment
      - name: runtime
        image: ddartifacts-docker.jfrog.io/runtime:v0.1.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 10m
            memory: 48Mi
          requests:
            cpu: 10m
            memory: 48Mi
        volumeMounts:
        - name: runtime-volume
          mountPath: /srv/runtime
