apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
  labels:
    service: {{ .Chart.Name }}
    app: web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    service: {{ .Chart.Name }}
    app: web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
