apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
  labels:
    service: {{ .Chart.Name }}
    app: web
    # https://docs.helm.sh/chart_best_practices/#labels
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    service: {{ .Chart.Name }}
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
