apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web
  labels:
    service: {{ .Chart.Name }}
    app: web
    # https://docs.helm.sh/chart_best_practices/#labels
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}
      app: web
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}
        app: web
        # https://docs.helm.sh/chart_best_practices/#labels
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      volumes:
      - name: runtime-volume
        emptyDir: {}
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command: ["/home/app/entrypoint.sh"]
        args: ["/home/app/run.sh"]
        resources:
{{ toYaml .Values.web.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        volumeMounts:
          - name: runtime-volume
            mountPath: /srv/runtime
            readOnly: true
        envFrom:
        - secretRef:
            name: {{ .Chart.Name }}-aws-credentials
        - configMapRef:
            name: {{ .Chart.Name }}-environment
      - name: runtime
        image: ddartifacts-docker.jfrog.io/runtime:v0.1.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 25m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: global-runtime-environment
        volumeMounts:
        - name: runtime-volume
          mountPath: /srv/runtime
